"""
Analyze LINEAR and EXPONENTIAL slopes.

This script:
    - builds the EXP-LINEAR slope plotting table
    - merges the chosen model from the model-selection analysis
    - analyzes LINEAR/EXP slope-direction agreement
    - plots effective-slope comparisons and slope distributions

Function-curve plots are generated by separate dedicated scripts.
"""

import argparse
from pathlib import Path

import matplotlib.pyplot as plt
import pandas as pd

from source_code.analysis.exp_lin_analysis.exp_lin_analysis_constants import *
from source_code.analysis.plot_utils import compute_effective_slope, compute_exp_rate, ensure_dir, get_ordered_counts, plot_bar_counts, save_close, to_float
from source_code.logger import log_run


def save_table(df: pd.DataFrame, out_file: Path, output_paths: list[str]) -> None:
    df.to_csv(out_file, index=False)
    output_paths.append(out_file.as_posix())


def infer_sign(value: float) -> str:
    if pd.isna(value):
        return SIGN_MISSING_LABEL
    if value > 0:
        return POSITIVE_SLOPE_LABEL
    if value < 0:
        return NEGATIVE_SLOPE_LABEL
    return ZERO_SLOPE_LABEL


def build_ignore_aicc_table(baseline_model_summary_df: pd.DataFrame) -> pd.DataFrame:
    ignore_df: pd.DataFrame = baseline_model_summary_df[baseline_model_summary_df[LABEL_FUNC_TYPE_COL] == LABEL_IGNORE].copy()
    ignore_df[AICC_COL] = pd.to_numeric(ignore_df[AICC_COL], errors="coerce")
    ignore_df = ignore_df.groupby(FAMILY_NAME_COL, as_index=False)[AICC_COL].min()
    return ignore_df.rename(columns={AICC_COL: IGNORE_AICC_COL})


def build_chosen_model_table(chosen_model_df: pd.DataFrame) -> pd.DataFrame:
    chosen_df: pd.DataFrame = chosen_model_df[[FAMILY_NAME_COL, CHOSEN_FUNCTION_LABEL_COL]].copy()

    if chosen_df[FAMILY_NAME_COL].duplicated().any():
        duplicated_families: list[str] = chosen_df.loc[chosen_df[FAMILY_NAME_COL].duplicated(keep=False), FAMILY_NAME_COL].astype(str).unique().tolist()
        raise ValueError(f"Duplicate families in chosen-model table: {duplicated_families}")

    return chosen_df.rename(columns={CHOSEN_FUNCTION_LABEL_COL: OVERALL_CHOSEN_MODEL_COL})


def calculate_exp_effective_slope(row: pd.Series) -> float:
    min_chr: float = to_float(row[MIN_CHROM_COL])
    max_chr: float = to_float(row[MAX_CHROM_COL])
    exp_p1: float = to_float(row[EXP_P1_COL])
    exp_p2: float = to_float(row[EXP_P2_COL])
    rate_at_min: float = to_float(compute_exp_rate(min_chr, exp_p1, exp_p2))
    rate_at_max: float = to_float(compute_exp_rate(max_chr, exp_p1, exp_p2))
    return compute_effective_slope(rate_at_min, rate_at_max, min_chr, max_chr)


def build_plotting_table(core_df: pd.DataFrame, features_df: pd.DataFrame, baseline_model_summary_df: pd.DataFrame, chosen_model_df: pd.DataFrame) -> pd.DataFrame:
    ignore_aicc_df: pd.DataFrame = build_ignore_aicc_table(baseline_model_summary_df)
    chosen_small_df: pd.DataFrame = build_chosen_model_table(chosen_model_df)
    features_small_df: pd.DataFrame = features_df[[FAMILY_NAME_COL, MIN_CHROM_COL, MAX_CHROM_COL]].drop_duplicates(subset=[FAMILY_NAME_COL]).copy()

    plotting_df: pd.DataFrame = core_df[[FAMILY_NAME_COL, M0_AICC_COL, M1_LINEAR_AICC_COL, M1_EXP_AICC_COL, EXP_P1_COL, EXP_P2_COL, LINEAR_P1_COL, LINEAR_P2_COL]].copy()
    plotting_df = plotting_df.rename(columns={M0_AICC_COL: CONSTANT_AICC_COL, M1_LINEAR_AICC_COL: LINEAR_AICC_COL, M1_EXP_AICC_COL: EXP_AICC_COL})
    plotting_df = plotting_df.merge(ignore_aicc_df, on=FAMILY_NAME_COL, how="left", validate="one_to_one")
    plotting_df = plotting_df.merge(features_small_df, on=FAMILY_NAME_COL, how="left", validate="one_to_one")
    plotting_df = plotting_df.merge(chosen_small_df, on=FAMILY_NAME_COL, how="left", validate="one_to_one")

    missing_chosen_mask: pd.Series = plotting_df[OVERALL_CHOSEN_MODEL_COL].isna()
    if missing_chosen_mask.any():
        missing_families: list[str] = plotting_df.loc[missing_chosen_mask, FAMILY_NAME_COL].astype(str).tolist()
        raise ValueError(f"Families missing from chosen-model table: {missing_families}")

    numeric_columns: list[str] = [CONSTANT_AICC_COL, LINEAR_AICC_COL, EXP_AICC_COL, IGNORE_AICC_COL, EXP_P1_COL, EXP_P2_COL, LINEAR_P1_COL, LINEAR_P2_COL, MIN_CHROM_COL, MAX_CHROM_COL]
    for column in numeric_columns:
        plotting_df[column] = pd.to_numeric(plotting_df[column], errors="coerce")

    plotting_df[EXP_EFFECTIVE_SLOPE_COL] = plotting_df.apply(calculate_exp_effective_slope, axis=1)

    preferred_columns: list[str] = [
        FAMILY_NAME_COL,
        OVERALL_CHOSEN_MODEL_COL,
        CONSTANT_AICC_COL,
        LINEAR_AICC_COL,
        EXP_AICC_COL,
        IGNORE_AICC_COL,
        EXP_P1_COL,
        EXP_P2_COL,
        EXP_EFFECTIVE_SLOPE_COL,
        LINEAR_P1_COL,
        LINEAR_P2_COL,
        MIN_CHROM_COL,
        MAX_CHROM_COL,
    ]

    return plotting_df[preferred_columns].sort_values(FAMILY_NAME_COL).reset_index(drop=True)


def plot_sign_agreement_counts(plotting_df: pd.DataFrame, transition_label: str, tables_dir: Path, plots_dir: Path, output_paths: list[str]) -> None:
    relevant_df: pd.DataFrame = plotting_df[(plotting_df[LINEAR_AICC_COL] < plotting_df[CONSTANT_AICC_COL]) & (plotting_df[EXP_AICC_COL] < plotting_df[CONSTANT_AICC_COL])].copy()
    relevant_df["linear_sign"] = relevant_df[LINEAR_P2_COL].apply(lambda value: infer_sign(to_float(value)))
    relevant_df["exp_sign"] = relevant_df[EXP_P2_COL].apply(lambda value: infer_sign(to_float(value)))
    relevant_df[SIGN_AGREEMENT_STATUS_COL] = SIGN_MISSING_LABEL

    valid_mask: pd.Series = relevant_df["linear_sign"].isin([POSITIVE_SLOPE_LABEL, NEGATIVE_SLOPE_LABEL]) & relevant_df["exp_sign"].isin([POSITIVE_SLOPE_LABEL, NEGATIVE_SLOPE_LABEL])
    relevant_df.loc[valid_mask & (relevant_df["linear_sign"] == relevant_df["exp_sign"]), SIGN_AGREEMENT_STATUS_COL] = SIGN_AGREEMENT_LABEL
    relevant_df.loc[valid_mask & (relevant_df["linear_sign"] != relevant_df["exp_sign"]), SIGN_AGREEMENT_STATUS_COL] = SIGN_DISAGREEMENT_LABEL

    counts: pd.Series = get_ordered_counts(relevant_df[SIGN_AGREEMENT_STATUS_COL], order=SIGN_AGREEMENT_ORDER)
    total_count: int = int(counts.sum())
    counts_df: pd.DataFrame = pd.DataFrame({SIGN_AGREEMENT_STATUS_COL: counts.index, "count": counts.values, "percentage": [round(100 * count / total_count, 2) if total_count > 0 else 0.0 for count in counts.values]})

    save_table(counts_df, tables_dir / f"{transition_label}_sign_agreement_counts.csv", output_paths)

    out_file: Path = plots_dir / f"{transition_label}_sign_agreement_counts_bar.png"
    plot_bar_counts(counts, f"{transition_label}: LINEAR/EXP sign agreement", "Sign agreement status", "Number of families", out_file, rotation=20, color_map=SIGN_AGREEMENT_COLOR_MAP)
    output_paths.append(out_file.as_posix())


def plot_effective_slope_scatter(plotting_df: pd.DataFrame, transition_label: str, plots_dir: Path, output_paths: list[str]) -> None:
    plot_df: pd.DataFrame = plotting_df.copy()
    plot_df[LINEAR_EFFECTIVE_SLOPE_COL] = pd.to_numeric(plot_df[LINEAR_P2_COL], errors="coerce")
    plot_df[EXP_EFFECTIVE_SLOPE_COL] = pd.to_numeric(plot_df[EXP_EFFECTIVE_SLOPE_COL], errors="coerce")
    plot_df = plot_df.dropna(subset=[LINEAR_EFFECTIVE_SLOPE_COL, EXP_EFFECTIVE_SLOPE_COL])

    if plot_df.empty:
        return

    fig, ax = plt.subplots(figsize=(8, 7))

    for model_label in MODEL_LABELS_WITH_EXP:
        model_df: pd.DataFrame = plot_df[plot_df[OVERALL_CHOSEN_MODEL_COL] == model_label]
        if not model_df.empty:
            ax.scatter(model_df[LINEAR_EFFECTIVE_SLOPE_COL], model_df[EXP_EFFECTIVE_SLOPE_COL], label=model_label, alpha=0.75, color=MODEL_COLOR_MAP.get(model_label))

    min_axis: float = min(plot_df[LINEAR_EFFECTIVE_SLOPE_COL].min(), plot_df[EXP_EFFECTIVE_SLOPE_COL].min())
    max_axis: float = max(plot_df[LINEAR_EFFECTIVE_SLOPE_COL].max(), plot_df[EXP_EFFECTIVE_SLOPE_COL].max())
    axis_padding: float = 0.05 * (max_axis - min_axis) if max_axis > min_axis else 1.0
    min_axis -= axis_padding
    max_axis += axis_padding

    ax.axvline(0, color="black", linewidth=1.0, linestyle="--")
    ax.axhline(0, color="black", linewidth=1.0, linestyle="--")
    ax.plot([min_axis, max_axis], [min_axis, max_axis], color="black", linewidth=1.0, linestyle=":")
    ax.set_xlim(min_axis, max_axis)
    ax.set_ylim(min_axis, max_axis)
    ax.set_title(f"{transition_label}: LINEAR vs EXP effective slopes")
    ax.set_xlabel("LINEAR effective slope")
    ax.set_ylabel("EXP effective slope")
    ax.legend(title="Overall chosen model")

    out_file: Path = plots_dir / f"{transition_label}_effective_slope_scatter.png"
    save_close(fig, out_file)
    output_paths.append(out_file.as_posix())


def plot_histogram_with_zero_and_median(values: pd.Series, title: str, xlabel: str, color: str, out_file: Path, output_paths: list[str]) -> None:
    clean_values: pd.Series = pd.to_numeric(values, errors="coerce").dropna()

    if clean_values.empty:
        return

    median_value: float = float(clean_values.median())
    fig, ax = plt.subplots(figsize=(8, 6))
    ax.hist(clean_values, bins=30, color=color, alpha=0.8)
    ax.axvline(0, color="black", linestyle="--", linewidth=1, label="Zero")
    ax.axvline(median_value, color="black", linewidth=1.8, label=f"Median = {median_value:.3g}")
    ax.set_title(f"{title} (n={len(clean_values)})")
    ax.set_xlabel(xlabel)
    ax.set_ylabel("Number of families")
    ax.legend()

    save_close(fig, out_file)
    output_paths.append(out_file.as_posix())


def plot_slope_histograms(plotting_df: pd.DataFrame, transition_label: str, plots_dir: Path, output_paths: list[str]) -> None:
    exp_chosen_df: pd.DataFrame = plotting_df[plotting_df[OVERALL_CHOSEN_MODEL_COL] == LABEL_EXP]
    linear_chosen_df: pd.DataFrame = plotting_df[plotting_df[OVERALL_CHOSEN_MODEL_COL] == LABEL_LINEAR]

    plot_histogram_with_zero_and_median(exp_chosen_df[EXP_EFFECTIVE_SLOPE_COL], f"{transition_label}: EXP effective slopes (EXP-chosen families)", "EXP effective slope", MODEL_COLOR_MAP[LABEL_EXP], plots_dir / f"{transition_label}_exp_chosen_effective_slope_histogram.png", output_paths)
    plot_histogram_with_zero_and_median(linear_chosen_df[LINEAR_P2_COL], f"{transition_label}: LINEAR slopes (LINEAR-chosen families)", "LINEAR slope", MODEL_COLOR_MAP[LABEL_LINEAR], plots_dir / f"{transition_label}_linear_chosen_slope_histogram.png", output_paths)


def plot_constant_comparison_slope_overlay_histogram(plotting_df: pd.DataFrame, transition_label: str, plots_dir: Path, output_paths: list[str]) -> None:
    linear_beats_constant: pd.Series = plotting_df[LINEAR_AICC_COL] < plotting_df[CONSTANT_AICC_COL]
    exp_beats_constant: pd.Series = plotting_df[EXP_AICC_COL] < plotting_df[CONSTANT_AICC_COL]
    linear_slopes: pd.Series = pd.to_numeric(plotting_df.loc[linear_beats_constant, LINEAR_P2_COL], errors="coerce").dropna()
    exp_slopes: pd.Series = pd.to_numeric(plotting_df.loc[exp_beats_constant, EXP_EFFECTIVE_SLOPE_COL], errors="coerce").dropna()

    if linear_slopes.empty and exp_slopes.empty:
        return

    fig, ax = plt.subplots(figsize=(8, 6))

    if not linear_slopes.empty:
        linear_median: float = float(linear_slopes.median())
        ax.hist(linear_slopes, bins=30, color=MODEL_COLOR_MAP[LABEL_LINEAR], alpha=0.45, label=f"LINEAR beats constant (n={len(linear_slopes)})")
        ax.axvline(linear_median, color=MODEL_COLOR_MAP[LABEL_LINEAR], linewidth=1.8, label=f"LINEAR median = {linear_median:.3g}")

    if not exp_slopes.empty:
        exp_median: float = float(exp_slopes.median())
        ax.hist(exp_slopes, bins=30, color=MODEL_COLOR_MAP[LABEL_EXP], alpha=0.45, label=f"EXP beats constant (n={len(exp_slopes)})")
        ax.axvline(exp_median, color=MODEL_COLOR_MAP[LABEL_EXP], linewidth=1.8, label=f"EXP median = {exp_median:.3g}")

    ax.axvline(0, color="black", linestyle="--", linewidth=1, label="Zero")
    ax.text(
        0.98,
        0.98,
        f"Only LINEAR beats constant: n={int((linear_beats_constant & ~exp_beats_constant).sum())}\nOnly EXP beats constant: n={int((exp_beats_constant & ~linear_beats_constant).sum())}\nBoth beat constant: n={int((linear_beats_constant & exp_beats_constant).sum())}",
        transform=ax.transAxes,
        ha="right",
        va="top",
        fontsize=9,
        bbox=dict(boxstyle="round", facecolor="white", edgecolor="black", alpha=0.9),
    )
    ax.set_title(f"{transition_label}: slope distributions among models that beat constant")
    ax.set_xlabel("Effective slope")
    ax.set_ylabel("Number of families")
    ax.legend(loc="upper left")

    out_file: Path = plots_dir / f"{transition_label}_linear_exp_beats_constant_slope_overlay_histogram.png"
    save_close(fig, out_file)
    output_paths.append(out_file.as_posix())


def plot_overall_chosen_slope_overlay_histogram(plotting_df: pd.DataFrame, transition_label: str, plots_dir: Path, output_paths: list[str]) -> None:
    linear_chosen_mask: pd.Series = plotting_df[OVERALL_CHOSEN_MODEL_COL] == LABEL_LINEAR
    exp_chosen_mask: pd.Series = plotting_df[OVERALL_CHOSEN_MODEL_COL] == LABEL_EXP
    linear_slopes: pd.Series = pd.to_numeric(plotting_df.loc[linear_chosen_mask, LINEAR_P2_COL], errors="coerce").dropna()
    exp_slopes: pd.Series = pd.to_numeric(plotting_df.loc[exp_chosen_mask, EXP_EFFECTIVE_SLOPE_COL], errors="coerce").dropna()

    if linear_slopes.empty and exp_slopes.empty:
        return

    fig, ax = plt.subplots(figsize=(8, 6))

    if not linear_slopes.empty:
        linear_median: float = float(linear_slopes.median())
        ax.hist(linear_slopes, bins=30, color=MODEL_COLOR_MAP[LABEL_LINEAR], alpha=0.45, label=f"LINEAR chosen overall (n={len(linear_slopes)})")
        ax.axvline(linear_median, color=MODEL_COLOR_MAP[LABEL_LINEAR], linewidth=1.8, label=f"LINEAR median = {linear_median:.3g}")

    if not exp_slopes.empty:
        exp_median: float = float(exp_slopes.median())
        ax.hist(exp_slopes, bins=30, color=MODEL_COLOR_MAP[LABEL_EXP], alpha=0.45, label=f"EXP chosen overall (n={len(exp_slopes)})")
        ax.axvline(exp_median, color=MODEL_COLOR_MAP[LABEL_EXP], linewidth=1.8, label=f"EXP median = {exp_median:.3g}")

    ax.axvline(0, color="black", linestyle="--", linewidth=1, label="Zero")
    ax.text(
        0.98,
        0.98,
        f"LINEAR chosen overall: n={int(linear_chosen_mask.sum())}\nEXP chosen overall: n={int(exp_chosen_mask.sum())}",
        transform=ax.transAxes,
        ha="right",
        va="top",
        fontsize=9,
        bbox=dict(boxstyle="round", facecolor="white", edgecolor="black", alpha=0.9),
    )
    ax.set_title(f"{transition_label}: slope distributions of overall chosen models")
    ax.set_xlabel("Slope")
    ax.set_ylabel("Number of families")
    ax.legend(loc="upper left")

    out_file: Path = plots_dir / f"{transition_label}_linear_exp_overall_chosen_slope_overlay_histogram.png"
    save_close(fig, out_file)
    output_paths.append(out_file.as_posix())


def run_slope_analysis(transition_label: str, core_table_path: Path, features_summary_table_path: Path, baseline_model_summary_table_path: Path, chosen_model_file_path: Path, output_dir: Path | None = None) -> list[str]:
    output_dir = output_dir or ANALYSIS_DIR / EXPONENTIAL_VS_LINEAR_SUBDIR / transition_label / SLOPE_ANALYSIS_SUBDIR
    tables_dir: Path = output_dir / TABLES_SUBDIR
    plots_dir: Path = output_dir / PLOTS_SUBDIR

    for directory in [output_dir, tables_dir, plots_dir]:
        ensure_dir(directory)

    core_df: pd.DataFrame = pd.read_csv(core_table_path)
    features_df: pd.DataFrame = pd.read_csv(features_summary_table_path)
    baseline_model_summary_df: pd.DataFrame = pd.read_csv(baseline_model_summary_table_path)
    chosen_model_df: pd.DataFrame = pd.read_csv(chosen_model_file_path)

    output_paths: list[str] = []
    plotting_df: pd.DataFrame = build_plotting_table(core_df, features_df, baseline_model_summary_df, chosen_model_df)

    save_table(plotting_df, tables_dir / f"{transition_label}_exp_lin_slope_plotting_table.csv", output_paths)
    plot_sign_agreement_counts(plotting_df, transition_label, tables_dir, plots_dir, output_paths)
    plot_effective_slope_scatter(plotting_df, transition_label, plots_dir, output_paths)
    plot_slope_histograms(plotting_df, transition_label, plots_dir, output_paths)
    plot_constant_comparison_slope_overlay_histogram(plotting_df, transition_label, plots_dir, output_paths)
    plot_overall_chosen_slope_overlay_histogram(plotting_df, transition_label, plots_dir, output_paths)

    return output_paths


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Analyze EXP versus LINEAR slopes.")
    parser.add_argument("--transition-label", "--transition_label", dest="transition_label", required=True)
    parser.add_argument("--core-table-path", "--core_table_path", dest="core_table_path", type=Path, required=True)
    parser.add_argument("--features-summary-table-path", "--features_summary_table_path", dest="features_summary_table_path", type=Path, required=True)
    parser.add_argument("--baseline-model-summary-table-path", "--baseline_model_summary_table_path", dest="baseline_model_summary_table_path", type=Path, required=True)
    parser.add_argument("--chosen-model-file-path", "--chosen_model_file_path", dest="chosen_model_file_path", type=Path, required=True)
    parser.add_argument("--output-dir", "--output_dir", dest="output_dir", type=Path, default=None)
    return parser.parse_args()


def main() -> None:
    args: argparse.Namespace = parse_args()

    output_paths: list[str] = run_slope_analysis(
        transition_label=args.transition_label,
        core_table_path=args.core_table_path,
        features_summary_table_path=args.features_summary_table_path,
        baseline_model_summary_table_path=args.baseline_model_summary_table_path,
        chosen_model_file_path=args.chosen_model_file_path,
        output_dir=args.output_dir,
    )

    log_run(
        step="exp_linear_slope_analysis",
        script=Path(__file__),
        params={
            "transition_label": args.transition_label,
            "core_table_path": args.core_table_path,
            "features_summary_table_path": args.features_summary_table_path,
            "baseline_model_summary_table_path": args.baseline_model_summary_table_path,
            "chosen_model_file_path": args.chosen_model_file_path,
            "output_dir": args.output_dir,
        },
        outputs=output_paths,
        description="Analyzed LINEAR and EXPONENTIAL slopes under the integrated CONSTANT-LINEAR-EXPONENTIAL-IGNORE comparison.",
        notes="Chosen models were read from the existing model-selection output. Function curves are generated by dedicated scripts.",
    )

    print("[✓] EXP-LINEAR slope analysis completed.")
    for output_path in output_paths:
        print(output_path)


if __name__ == "__main__":
    main()